# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2018-04-23 02:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempsensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_x', models.FloatField(default=0, max_length=6, verbose_name='X\u4e2d\u5fc3')),
                ('center_y', models.FloatField(default=0, max_length=6, verbose_name='Y\u4e2d\u5fc3')),
                ('time', models.DateTimeField(default=datetime.datetime(2018, 4, 23, 10, 46, 41, 652000))),
            ],
            options={
                'ordering': ('time',),
            },
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ('y', 'x')},
        ),
    ]
