# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2018-04-27 13:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempsensor', '0002_auto_20180423_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempcenter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 21, 12, 27, 17441)),
        ),
    ]
