# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2018-05-13 09:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempsensor', '0003_auto_20180510_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempcenter',
            name='angle',
            field=models.FloatField(default=0, max_length=6, verbose_name='\u89d2\u5ea6'),
        ),
        migrations.AddField(
            model_name='tempcenter',
            name='distance',
            field=models.FloatField(default=0, max_length=6, verbose_name='\u504f\u5fc3\u8ddd'),
        ),
        migrations.AddField(
            model_name='tempcenter',
            name='region',
            field=models.CharField(choices=[('1', '\u7b2c\u4e00\u8c61\u9650'), ('2', '\u7b2c\u4e8c\u8c61\u9650'), ('3', '\u7b2c\u4e09\u8c61\u9650'), ('4', '\u7b2c\u56db\u8c61\u9650')], default='1', max_length=2, verbose_name='\u6240\u5728\u8c61\u9650'),
        ),
        migrations.AlterField(
            model_name='tempcenter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 13, 17, 18, 32, 279000)),
        ),
    ]
