# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2018-04-29 09:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempsensor', '0003_auto_20180427_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempcenter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 17, 6, 32, 108840)),
        ),
    ]
