# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2018-05-10 14:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempsensor', '0004_auto_20180429_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempcenter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 10, 22, 32, 5, 994138)),
        ),
        migrations.AlterField(
            model_name='tempvalue',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
